language: ruby
cache: bundler

rvm:
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 2.0.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - mike@tomkobombco.com
    on_failure: change
    on_success: never
